name: CI

on:
  push:
    branches:
      - development
  pull_request:
    branches:
      - "**"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 1
    - name: Test and Build
      run: |
        cd client
        yarn install
        yarn lint
        yarn test
        yarn build
